name: .NET 9.0 CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 9.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Debug folder structure
      run: dir/s

    - name: Restore dependencies
      run: dotnet restore CyberSecurityChatbot.csproj
      working-directory: ST10438308_PROG6221_Part1/CyberSecurityChatbot

    - name: Build
      run: dotnet build CyberSecurityChatbot.csproj --configuration Release
      working-directory: ST10438308_PROG6221_Part1/CyberSecurityChatbot

    - name: Run tests
      run: dotnet test CyberSecurityChatbot.csproj
      working-directory: ST10438308_PROG6221_Part1/CyberSecurityChatbot

    - name: Run basic checks
      run: echo "Build completed for .NET 9!"
