name: .NET Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore CyberSecurityChatbot/CyberSecurityChatbot.csproj

    - name: Build
      run: dotnet build CyberSecurityChatbot/CyberSecurityChatbot.csproj --configuration Release