name: .NET 9.0 CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 9.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore CyberSecurityChatbot/CyberSecurityChatbot.csproj

    - name: Build
      run: dotnet build CyberSecurityChatbot/CyberSecurityChatbot.csproj --configuration Release
      
    - name: Run tests
      run: dotnet test CyberSecurityChatbot/CyberSecurityChatbot.csproj

    - name: Run basic checks
      run: echo "Build completed for .NET 9!"
